List<String> states = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telengana",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli",
  "NCT Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry/Pondicherry"
];

Map<String,List<String>> cities= {
  "Andhra Pradesh" : [],
  "Arunachal Pradesh" : [],
  "Assam" : [],
  "Bihar" : [],
  "Chhattisgarh" :[],
  "Goa" : [],
  "Gujarat" : [],
  "Haryana" : [],
  "Himachal Pradesh" : [],
  "Jharkhand" : [],
  "Karnataka" : [],
  "Kerala" :[],
  "Madhya Pradesh" : [],
  "Maharashtra" : [],
  "Manipur" : [],
  "Meghalaya" : [],
  "Mizoram" : [],
  "Nagaland" : [],
  "Odisha" : [],
  "Punjab" : [],
  "Rajasthan" : [],
  "Sikkim" : [],
  "Tamil Nadu" : [],
  "Telengana" : [],
  "Tripura" : [],
  "Uttarakhand" : [],
  "Uttar Pradesh" : [],
  "West Bengal" : [],
  "Andaman and Nicobar Islands" : [],
  "Chandigarh" : [],
  "Dadra and Nagar Haveli" : [],
  "NCT Delhi" : [],
  "Jammu and Kashmir" : [],
  "Ladakh" : [],
  "Lakshadweep" :[],
  "Puducherry/Pondicherry" : [],
};


